# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Login to dockerhub
      inputs:
        command: login
        containerRegistry: Dockerhub-connection
    
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: niraj5aug/model_deployment01
        tags: |
          md01